[Interface]
PrivateKey = 8KV7MiOMDMpyu/pIdK0k853NMutNBZA7KC7Y2LFTynM=
Address = 192.168.3.13/32
DNS = 10.11.1.20,10.11.1.21
MTU = 1280

[Peer]
PublicKey = BBFxDe3yzCDL+C0j3kAFommYonZCthcOmEqQ3D+AzFo=
AllowedIPs = 0.0.0.0/0
Endpoint = 103.147.222.243:51820
PersistentKeepalive = 25
