apiVersion: apps/v1
kind: Deployment
metadata:
  name: dude-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dude-bot
  template:
    metadata:
      labels:
        app: dude-bot
    spec:
      containers:
      - name: dude-bot
        image: 509342715088.dkr.ecr.ap-southeast-1.amazonaws.com/sanditel-dude:b61e0d6
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
      # - name: wireguard
      #   image: linuxserver/wireguard
      #   env:
      #   - name: PUID
      #     value: "1000"
      #   - name: PGID
      #     value: "1000"
      #   securityContext:
      #     capabilities:
      #       add:
      #       - NET_ADMIN
      #   volumeMounts:
      #   - name: wg-config
      #     mountPath: /config
      
      # volumes:
      # - name: wg-config
      #   secret:
      #     secretName: wg-config
---
apiVersion: v1
kind: Service
metadata:
  name: dude-service
spec:
  selector:
    app: dude-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer 