apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: sanditel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
      - name: frontend-web
        image: 509342715088.dkr.ecr.ap-southeast-1.amazonaws.com/sanditel-frontend:4f99b96d
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web-svc
  namespace: sanditel
spec:
  type: LoadBalancer # Biar dikasih IP Publik/DNS sama AWS
  selector:
    app: frontend-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000